# Generated by Django 2.2.6 on 2019-10-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'MODULO',
            },
        ),
        migrations.CreateModel(
            name='Digiturno_ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('rango_ini', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digiturno_app.Modulo')),
            ],
            options={
                'db_table': 'DIGITURNO_REF',
            },
        ),
        migrations.CreateModel(
            name='Digiturno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_turno', models.IntegerField()),
                ('atendido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digiturno_app.Modulo')),
            ],
            options={
                'db_table': 'DIGITURNO',
            },
        ),
    ]
