# Generated by Django 2.2.6 on 2019-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0003_servicio_key_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='turno',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
