# Generated by Django 2.2.6 on 2019-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0004_modulo_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='digiturno',
            name='letra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
