# Generated by Django 2.2.6 on 2019-10-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0005_digiturno_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digiturno',
            name='letra',
        ),
        migrations.AddField(
            model_name='servicio',
            name='letra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
