# Generated by Django 2.2.6 on 2019-10-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0007_auto_20191010_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digiturno_app.Servicio')),
            ],
            options={
                'db_table': 'TURNO',
            },
        ),
    ]
