# Generated by Django 2.2.6 on 2019-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0008_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='digiturno',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
