# Generated by Django 2.2.6 on 2019-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0011_listado_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='digiturno',
            name='aviso',
            field=models.BooleanField(default=False),
        ),
    ]
