# Generated by Django 2.2.6 on 2019-10-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0013_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
    ]
