# Generated by Django 2.2.6 on 2019-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0014_remove_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
