# Generated by Django 2.2.6 on 2019-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0015_modulo_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color',
            field=models.CharField(default=-5, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='icon',
            field=models.CharField(default=-5, max_length=30),
            preserve_default=False,
        ),
    ]
