# Generated by Django 2.2.6 on 2019-10-14 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0017_auto_20191014_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
