# Generated by Django 2.2.6 on 2019-10-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0018_auto_20191014_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ESPECIALIDAD',
            },
        ),
        migrations.AddField(
            model_name='digiturno',
            name='llamado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digiturno_app.Especialidad')),
            ],
            options={
                'db_table': 'AGENDA',
            },
        ),
    ]
