# Generated by Django 2.2.6 on 2019-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0019_auto_20191030_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digiturno',
            name='atendido',
            field=models.BooleanField(default=True),
        ),
    ]
