# Generated by Django 2.2.6 on 2019-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0020_auto_20191030_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digiturno',
            name='atendido',
        ),
        migrations.AddField(
            model_name='digiturno',
            name='atencion',
            field=models.BooleanField(default=False),
        ),
    ]
