# Generated by Django 2.2.6 on 2019-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0021_auto_20191030_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='horario_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
