# Generated by Django 2.2.6 on 2019-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0022_servicio_horario_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='horario',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
