# Generated by Django 2.2.6 on 2019-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiturno_app', '0023_servicio_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default=-5, max_length=60),
            preserve_default=False,
        ),
    ]
